server:
  port: 8085
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.49
    max-threads-for-peer-replication: 0
  instance:
    hostname: localhost