server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #自动映射eureka下的服务路由
          enabled: true
          #开启服务名称小写
          lower-case-service-id: true
          #服务熔断降级
#          default-filters:
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback

    discovery:
      enabled: true
      # 注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8085/eureka/
#  instance:
#    prefer-ip-address: true
#hystrix熔断器，3秒后自动超时
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000